In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/My Drive/Amazon_Unlocked_Mobile.csv")
df.head()

Product Name  ... Review Votes
0  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...  ...          1.0
1  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...  ...          0.0
2  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...  ...          0.0
3  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...  ...          0.0
4  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...  ...          0.0

[5 rows x 6 columns]

In [ ]:
df=df[['Reviews','Rating']]

In [ ]:
df.head()

Reviews  Rating
0  I feel so LUCKY to have found this used (phone...       5
1  nice phone, nice up grade from my pantach revu...       4
2                                       Very pleased       5
3  It works good but it goes slow sometimes but i...       4
4  Great phone to replace my lost phone. The only...       4

In [ ]:
df.isna()

Reviews  Rating
0         False   False
1         False   False
2         False   False
3         False   False
4         False   False
...         ...     ...
413835    False   False
413836    False   False
413837    False   False
413838    False   False
413839    False   False

[413840 rows x 2 columns]

In [ ]:
df = df.dropna(axis='rows')

In [ ]:
df.tail()

Reviews  Rating
413835                     another great deal great price       5
413836                                                 Ok       3
413837        Passes every drop test onto porcelain tile!       5
413838  I returned it because it did not meet my needs...       3
413839  Only downside is that apparently Verizon no lo...       4

In [ ]:
df=df[df['Rating']!=3]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 382015 entries, 0 to 413839
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   Reviews  382015 non-null  object
 1   Rating   382015 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 8.7+ MB


In [ ]:
df.reset_index(inplace = True) 

In [ ]:
df.tail()

index                                            Reviews  Rating
382010  413832  good rugged phone that has a long-lasting batt...       4
382011  413834                                          used hard       1
382012  413835                     another great deal great price       5
382013  413837        Passes every drop test onto porcelain tile!       5
382014  413839  Only downside is that apparently Verizon no lo...       4

In [ ]:

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer() 
import nltk
nltk.download('wordnet')
import re
nltk.download('stopwords')
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import embeddings
nltk.download('punkt')
from sklearn.manifold import TSNE
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
import numpy as np
from keras.models import  Sequential
from keras.layers import Embedding,Dropout,Dense,LSTM
import gensim

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


Using TensorFlow backend.


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
df.head()

index                                            Reviews  Rating
0      0  I feel so LUCKY to have found this used (phone...       5
1      1  nice phone, nice up grade from my pantach revu...       4
2      2                                       Very pleased       5
3      3  It works good but it goes slow sometimes but i...       4
4      4  Great phone to replace my lost phone. The only...       4

In [ ]:
df = df.dropna(axis='rows')
df.reset_index(inplace = True)

In [ ]:
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['Reviews'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review if not word in (stopwords.words("english"),"samsung","blu","apple","lg","blackberry","nokia","motorola","htc","cnpgd","otterbox","sony","posh mobile","huawei","lg electronics","polaroid","zte","alcatel","asus","verykool","casio","lenovo","ultrabox","rca","figo","pantech","samsung korea ltd","amazon.com")]
    review = ' '.join(review)
    corpus.append(review)
df["new_review"] = corpus
df.head()

In [ ]:
len(corpus)

In [ ]:
len(max(corpus))

In [ ]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# cv = TfidfVectorizer()
# onehot_repr = cv.fit_transform(corpus).toarray()

NameError: ignored

In [ ]:
voc_size = 10000
from tensorflow.keras.preprocessing.text import one_hot
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[9110,
  3821,
  5391,
  7310,
  738,
  5655,
  2909,
  8577,
  1873,
  788,
  738,
  499,
  4120,
  1873,
  4147,
  5715,
  6312,
  788,
  7664,
  4905,
  3937,
  9316,
  5941,
  1368,
  257,
  2367,
  8577,
  1303,
  3459,
  4799,
  5919,
  1281,
  5949,
  1303,
  8578,
  7892,
  6047,
  3323,
  7628,
  7469,
  257,
  7093,
  5639,
  6618,
  1285,
  8166,
  3072,
  3568,
  9373,
  8448,
  5770,
  4202,
  1569,
  3293,
  6009,
  1469,
  9412,
  1873,
  788,
  9110,
  8817,
  8577,
  9373,
  662,
  9872,
  980,
  2772,
  3937,
  691,
  9550],
 [789,
  788,
  789,
  6109,
  755,
  3937,
  3459,
  7095,
  4846,
  662,
  3356,
  3473,
  6109,
  257,
  2581,
  3473,
  6109,
  4299,
  2855,
  1285,
  9714,
  788,
  2772,
  2768,
  5371,
  5759,
  738,
  3974,
  8775,
  5333,
  4908,
  3377,
  8426,
  1794,
  257,
  8362,
  4951,
  8650,
  788],
 [662, 4699],
 [1569,
  6835,
  7592,
  2772,
  1569,
  3481,
  8334,
  3307,
  2772,
  1569,
  1850,
  662,
  7592,
  788,
  9110,
  545,
  1569],

In [ ]:
sent_length=140
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3937  691 9550]
 [   0    0    0 ... 4951 8650  788]
 [   0    0    0 ...    0  662 4699]
 ...
 [   0    0    0 ... 7107 8650 2582]
 [   0    0    0 ... 1429 1750 3846]
 [   0    0    0 ... 1325 7960  945]]


In [ ]:
df['labels']=np.where(df['Rating'] > 3, 1, 0)
df.head()

level_0  index  ...                                         new_review  labels
0        0      0  ...  i feel so lucky to have found this used phone ...       1
1        1      1  ...  nice phone nice up grade from my pantach revue...       1
2        2      2  ...                                       very pleased       1
3        3      3  ...  it work good but it go slow sometimes but it a...       1
4        4      4  ...  great phone to replace my lost phone the only ...       1

[5 rows x 6 columns]

In [ ]:
y=df['labels']

In [ ]:
X = df["new_review"]

In [ ]:

X.shape

(382015,)

In [ ]:
len(embedded_docs),y.shape

(382015, (382015,))

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.2.0'

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((382015, 140), (382015,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
embedding_vector_features=100
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 140, 100)          1000000   
_________________________________________________________________
dropout_1 (Dropout)          (None, 140, 100)          0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 1,080,501
Trainable params: 1,080,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=12,batch_size=32)


Train on 255950 samples, validate on 126065 samples
Epoch 1/2
191392/255950 [=====================>........] - ETA: 5:09 - loss: 0.0230 - accuracy: 0.9929

In [ ]:
y_pred=model.predict_classes(X_test)

NameError: ignored

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)